#! /bin/bash -

# TODO check if ac_drone image exists and if not, build it:
# for now, build it before running this script, by doing:
# docker build -t drone .

docker run -d --name="drone-ci" \
	-e "DRONE_SESSION_SECRET=$DRONE_SESSION_SECRET" \
	-e "DRONE_SESSION_EXPIRES=72h" \
	-e "DRONE_GITHUB_CLIENT=$DRONE_GITHUB_CLIENT" \
	-e "DRONE_GITHUB_SECRET=$DRONE_GITHUB_SECRET" \
	-v /var/lib/drone/ \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(pwd)/drone.sqlite:/var/lib/drone/drone.sqlite \
	-p 80:80 \
	drone
